---

# Manage Docker as a non-root user (affect after logout and logback, try "$ docker run hello-world")
- name: Present docker group, (manage docker as no-root user)
  group: name='{{ docker_group }}' state=present
- name: Add user to docker group, (manage docker as no-root user)
  user:
    name: "{{ dev_user }}"
    groups: '{{ docker_group }}'
    append: yes

# Configure Docker daemon
- name: Mkdir for Docker daemon file
  file: path=/etc/docker state=directory
- name: Configure Docker daemon
  template: src=daemon.json dest=/etc/docker/daemon.json

# - import_tasks: '{{ role_path }}/tasks/os_aware/config_registry.yml'

# Proxy Setting
- include_tasks: '{{ role_path }}/tasks/os_aware/proxy_setting.yml'

# Configure Docker to start on boot
- name: Docker daemon reload by systemd
  systemd:
    state: restarted
    enabled: true
    daemon_reload: yes
    name: docker
  failed_when: false
- name: Restart docker daemon
  service: name=docker state=restarted enabled=yes
