---

- name: Load os depended vars
  include_vars: '{{ item }}'
  with_first_found:
  - files:
      - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
      - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
      - '{{ ansible_distribution }}.yml'
      - '{{ ansible_os_family }}.yml'
      - 'default.yml'
    paths: '{{ role_path }}/vars/os'

- name: Install the dependence packages
  package: name="{{ item }}" state=present
  with_items: '{{ pkg_set.dependencies }}'

- name: Present samba directory
  file:
    path: '{{ smb_d.path }}'
    owner: '{{ smb_d.owner }}'
    group: '{{ smb_d.group }}'
    state: directory
    mode: '{{ smb_d.mode }}'
  with_items: "{{ smb_conf.dirs }}"
  loop_control:
    loop_var: smb_d

- name: Set samba configure file
  template:
    src: smb.conf.v4
    dest: /etc/samba/smb.conf
    backup: yes

- name: Set samba user account
  # shell: echo -e "{{ smb_conf.init_pwd + '\n' + smb_conf.init_pwd + '\n' }}" | pdbedit -t -a -u {{ dev_user }}
  # shell: echo {{ (ansible_distribution in ['Ubuntu', 'Debian']) | ternary(' ', '-e') }} '{{ smb_conf.init_pwd }}\n{{ smb_conf.init_pwd }}\n' | pdbedit -t -a -u {{ dev_user }}
  shell: printf '{{ smb_u.pwd }}\n{{ smb_u.pwd }}\n' | pdbedit -t -a -u {{ smb_u.name }}
  with_items: "{{ smb_conf.users }}"
  loop_control:
    loop_var: smb_u

- name: Restart samba service
  service: name={{ item }} state=started enabled=yes
  with_items: '{{ pkg_set.services }}'

- name: Check service status
  shell: "smbclient -L localhost -U={{ smb_u.name }}%{{ smb_u.pwd }}"
  become: true
  become_user: "{{ smb_u.name }}"
  register: smbc_res
  changed_when: False
  failed_when: "( smbc_res | failed )"
  loop_control:
    loop_var: smb_u
