---

- name: (CentOS) Update repo cache
  yum:
    update_cache: yes
    cache_valid_time: 3600
  failed_when: false
  changed_when: false
  ignore_errors: True
- name: (Debian) Update repo cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  failed_when: false
  changed_when: false
  ignore_errors: True

# - name: Remove old vnc packages
#   package: name="{{ item }}" state=absent
#   with_items: [tightvncserver]
- name: Install the packages (vnc + dm)
  package: name="{{ item }}" state=present
  with_items: '{{ vnc_s.vnc_pkgs | union(vnc_s.dm_pkgs) }}'
- name: Install the dm packages
  yum: name="{{ item }}" state=present
  with_items: '{{ vnc_s.yum_pkgs | default([]) }}'

- set_fact:
    # vnc_setpw_cmd: "echo {{ (ansible_distribution in ['Ubuntu', 'Debian']) | ternary(' ', '-e') }} '{{ vnc_init_pwd }}\n{{ vnc_init_pwd }}\n' | vncpasswd"
    vnc_setpw_cmd: "printf '{{ vnc_init_pwd }}\n{{ vnc_init_pwd }}\n' | vncpasswd"
    dev_user_vnc: "/home/{{ dev_user }}/.vnc"
- debug:
    msg: su - {{ dev_user }} -l -c "{{ vnc_setpw_cmd }}"
- name: Init vnc
  shell: "{{ vnc_setpw_cmd }}"
  register: initvnc_stat
  become: true
  become_user: "{{ dev_user }}"
- name: Present .vnc dir
  file:
    path: '{{ dev_user_vnc }}'
    owner: "{{ dev_user }}"
    group: "{{ dev_group }}"
    state: directory
    mode: 0755

- debug:
    var: initvnc_stat
- name: Backup xstartup
  block:
    - name: Check if .bk exist
      stat: path="{{ dev_user_vnc }}/xstartup.bk"
      register: bkstat
    - name: Check if xstartup exist
      stat: path="{{ dev_user_vnc }}/xstartup"
      register: xstat
    - name: Backup xstartup
      copy:
        remote_src: true
        src: "{{ dev_user_vnc }}/xstartup"
        dest: "{{ dev_user_vnc }}/xstartup.bk"
        owner: '{{ dev_user}}' 
        group: '{{ dev_group}}' 
        mode: 0770 
      when: (xstat.stat.exists) and ( not bkstat.stat.exists )

- name: Set xstartup by copy
  template:
    src: '{{ vnc_s.xstartup }}'
    dest: '{{ dev_user_vnc }}/{{ vnc_s.xstartup }}'
    owner: '{{ dev_user}}' 
    group: '{{ dev_group}}' 
    mode: 0770 
- name: Set xstartup
  template:
    src: '{{ vnc_s.xstartup }}'
    dest: '{{ dev_user_vnc }}/xstartup'
    owner: '{{ dev_user}}' 
    group: '{{ dev_group}}' 
    mode: 0770 
