---

- name: Install dependencies
  include_tasks: 'preinstall-{{ ansible_distribution_major_version }}.yml'

- name: Pick install script
  include_tasks: "install_using_{{ repo_install | ternary('repo', 'package') }}.yml"
