---

- name: (Swarm) Build start swarm command
  set_fact:
    swarm_init_cmds:
      init: "docker swarm init --advertise-addr {{ public_ip | default(ansible_host) }}"
      join_manager_gen_cmd: "docker swarm join-token manager | grep 'docker swarm join'"
      join_worker_gen_cmd: "docker swarm join-token worker | grep 'docker swarm join'"
- name: (Swarm) Print init commands
  debug:
    var: swarm_init_cmds
- name: (Swarm) Start first swarm node
  shell: "{{ swarm_init_cmds.init }}"
  register: swarm_init_result
  become: true
  become_user: "{{ dev_user}}"
- name: (Swarm) Fetch join manager command
  shell: "{{ swarm_init_cmds.join_manager_gen_cmd }}"
  register: swarm_join_manager_cmd_result
  become: true
  become_user: "{{ dev_user}}"
- name: (Swarm) Fetch join worker command
  shell: "{{ swarm_init_cmds.join_worker_gen_cmd }}"
  register: swarm_join_worker_cmd_result
  become: true
  become_user: "{{ dev_user}}"
- name: (Swarm) Gather join command on first manager
  set_fact:
    swarm_join_cmds_local:
      manager: "{{ swarm_join_manager_cmd_result.stdout | regex_replace('^[ \t]+') }}"
      worker: "{{ swarm_join_worker_cmd_result.stdout | regex_replace('^[ \t]+') }}"
- name: (Swarm) Print Join Commands
  debug:
    var: swarm_join_cmds_local
