---

- name: (Swarm) Other managers nodes join
  shell: "{{ swarm_join_cmds.manager }}"
  register: swarm_join_result
  become: true
  become_user: "{{ dev_user}}"
# - debug:
#     var: swarm_join_result
