---
- name: (Swarm) Other worker nodes join
  shell: "{{ swarm_join_cmds.worker }}"
  register: swarm_join_result
  become: true
  become_user: "{{ dev_user}}"
# - debug:
#     var: swarm_join_result
